# Site settings
title: Modern Mobile Developer &amp Entrepreneur
email: zholdiyarov@gmail.com
url: https://szholdiyarov.github.io/
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
skills: "Project Manager - Mobile Developer - Entrepreneur"
meta_author: Zholdiyarov Sanzhar

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 8E3B46 #80B3FF
  primary-rgb: "142,59,70" #"128,179,255"
  secondary: B2D3A8 #FD6E8A
  secondary-dark: 52B788 #A2122F

# Footer settings
footer:
  copyright: Sanzhar Zholdiyarov
  location: Almaty, Kazakhstan
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: stack-overflow
    url: http://stackoverflow.com/users/2912331/szholdiyarov
  - title: bitbucket
    url: https://bitbucket.org/szholdiyarov/
  - title: github
    url: https://github.com/szholdiyarov

# Postal address (add as many lines as necessary)
address:
  - line: Al-Farabi 21
  - line: Almaty, Kazakhstan

# Credits content
credits: 'To my wife and two lovely kids.'

# Build settings
markdown: kramdown
permalink: pretty

# post colors:
# post text: <font color="#334d4d"> 
# post urls in text: font color="#0a0f0f">

